version: '3.1'
services:
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/my_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=my_db
    healthcheck:
      test: ["CMD-SHELL","pq_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
